In [8]:
import re
import string
import pickle
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import TweetTokenizer

import wandb
from wandb.keras import WandbCallback

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

import tensorflow as tf
from tensorflow.keras import activations
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot, hashing_trick, text_to_word_sequence
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding, Dense, Activation, LSTM, Bidirectional, Conv1D, GlobalMaxPooling1D, MaxPooling1D, Dropout
from keras.backend import clear_session
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

from util import load_data, preprocessing, confusion_matrix_plot, evaluate, get_vocab_size, create_token2id, one_hot_text, get_verdict, get_verdict_with_token2id


[nltk_data] Downloading package stopwords to
[nltk_data]     /home/mhalvax/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /home/mhalvax/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [9]:
df = pd.read_csv("cleaned data - Sheet1.csv")
simple_df = df[["Original article text", "Verdict"]]

In [10]:
X = df["Original article text"].values
y = df["Verdict"].replace("FALSE",1).replace("TRUE",0).values

In [11]:
X_preproc = [preprocessing(i) for i in X]

print('Before: {}'.format(X[0]))
print('After: {}'.format(X_preproc[0]))

Before: SAN JUAN, PUERTO RICO — When things went bad during Hurricane Maria, they went bad all at once, across this entire island. Suddenly, everything was dysfunctional, including the power grid, the cellphone towers, the banking system. Even the disaster managers, the professionals in charge of responding to hurricanes, were forced to evacuate the buildings where they had sheltered during the powerful storm.

They shifted operations to the convention center here, an improvised maneuver that was just one of the reasons the government struggled to meet the challenges Maria presented. They were in the dark. The island’s residents were in the dark. No one knew the extent of what had happened — or what was happening — for days.

“Everything collapsed,” said Héctor Pesquera, the Puerto Rico governor’s director of safety and public protection. “Everything collapsed simultaneously.”

Nearly two weeks after Maria caused a historic catastrophe and thrust Puerto Rico into a humanitarian crisis,

In [22]:
cv = CountVectorizer()
X_cv = cv.fit_transform(X)

In [23]:
cv.get_feature_names_out()

AttributeError: 'CountVectorizer' object has no attribute 'get_feature_names_out'

In [21]:
print(X_cv.toarray())

[[2 0 0 ... 0 1 0]
 [1 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]
